l

diff --git a/.github/workflows/test-app.yml b/.github/workflows/test-app.yml
--- a/.github/workflows/test-app.yml
+++ b/.github/workflows/test-app.yml
@@ -38,7 +38,7 @@ jobs:
           exit 1
 
       - name: Run Cypress Tests
-        run: npx cypress run --reporter mochawesome  || echo "CYPRESS_FAILED=true" >> $GITHUB_ENV
+        run: npx cypress run --reporter mochawesome || echo "CYPRESS_FAILED=true" >> $GITHUB_ENV
 
       - name: Upload MochaAwesome Report (if failed)
         if: env.CYPRESS_FAILED == 'true'
@@ -48,15 +48,15 @@ jobs:
           path: cypress/results/mochawesome.html
 
       - name: Send Slack Notification with HTML Report (if failed)
-  if: env.CYPRESS_FAILED == 'true'
-  run: |
-    curl -F file=@cypress/results/mochawesome.html \
-         -F "initial_comment=🚨 Test run failed! Here's the report." \
-         -F channels=#your-channel \
-         -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
-         https://slack.com/api/files.upload
-  env:
-    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+        if: env.CYPRESS_FAILED == 'true'
+        run: |
+          curl -F file=@cypress/results/mochawesome.html \
+               -F "initial_comment=🚨 Test run failed! Here's the report." \
+               -F channels=#your-channel \
+               -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
+               https://slack.com/api/files.upload
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
 
       - name: Send Success Message (if passed)
         if: env.CYPRESS_FAILED != 'true'
